/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ff793e",
        "surface-container-low": "#ffede5",
        "surface-bright": "#fff4f0",
        "surface": "#fff4f0",
        "inverse-on-surface": "#cb906c",
        "error-container": "#fb5151",
        "on-error": "#ffefee",
        "error": "#b31b25",
        "tertiary": "#0058ba",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#a13900",
        "secondary-fixed": "#59ee50",
        "inverse-surface": "#1d0800",
        "error-dim": "#9f0519",
        "tertiary-dim": "#004da4",
        "on-primary-container": "#431300",
        "on-tertiary-fixed": "#00173a",
        "on-secondary": "#d2ffc4",
        "primary-container": "#ff793e",
        "secondary": "#006b0a",
        "surface-container-highest": "#ffd4bc",
        "tertiary-fixed": "#89b0ff",
        "on-primary-fixed": "#000000",
        "on-tertiary-container": "#002f69",
        "on-surface-variant": "#805031",
        "on-secondary-container": "#005406",
        "surface-container": "#ffe3d4",
        "on-surface": "#4b2409",
        "on-tertiary": "#f0f2ff",
        "surface-dim": "#ffc9aa",
        "secondary-container": "#59ee50",
        "background": "#fff4f0",
        "surface-container-high": "#ffdbc8",
        "secondary-dim": "#005d07",
        "primary-dim": "#8d3100",
        "tertiary-container": "#89b0ff",
        "on-primary-fixed-variant": "#521900",
        "primary": "#a13900",
        "tertiary-fixed-dim": "#71a2ff",
        "primary-fixed-dim": "#fe5f00",
        "on-tertiary-fixed-variant": "#003779",
        "inverse-primary": "#fe5f00",
        "on-error-container": "#570008",
        "secondary-fixed-dim": "#49e043",
        "outline-variant": "#dda07b",
        "on-secondary-fixed": "#003e03",
        "surface-variant": "#ffd4bc",
        "on-background": "#4b2409",
        "on-secondary-fixed-variant": "#005f07",
        "outline": "#a06b4a",
        "on-primary": "#ffefea"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Lexend"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
